### ISSUE TITLE
Why my password is automatically filled in the web browser?

### ISSUE THREAD

**Issue by elony314** [vlaci/openconnect-sso#18]
When I login, the browser pop up with my password filled in. I am using mac. Is this supposed to happen and how does it get my password?

**Comment by vlaci** [comment]
The password is saved to your keychain using the [keyring](https://pypi.org/project/keyring/) python package. If this behavior is undesirable to you, then remove your password from your keychain and leave out `--user` command line argument.

Currently there is no way to opt out from saving the password when it is entered in the command line.

**Comment by elony314** [comment]
I have just found out the part of code responsible for this before seeing your reply. Good to know this package. This is a desirable feature for me.
