### ISSUE TITLE
Save the authorization

### ISSUE THREAD

**Issue by dbenjaminmiller** [vlaci/openconnect-sso#22]
The script works, but I need to go through the process of the browser window every time. _And_ my org requires 2FA, so each time, I need to re-authenticate. Can the authorization be saved? For the record, the browser record automatically closes before I can hit the button which says "stay signed in", for whatever that's worth.

**Comment by vlaci** [comment]
You can comment or remove the rule that submits the form in your `~/.config/openconnect-sso/config.toml`
These are the lines responsible for submission:
```
[[auto_fill_rules."https://*"]]
selector = "input[type=submit]"
action = "click"
```

If ticking the checkbox helps in your case I can extend the code to automatically fill that checkbox by default

**Comment by vlaci** [comment]
Feel free to reopen if your issue is still not resolved.

**Comment by mluis7** [comment]
> If ticking the checkbox helps in your case I can extend the code to automatically fill that checkbox by default

For a workaround see
https://github.com/vlaci/openconnect-sso/issues/196
