### ISSUE TITLE
opeconnect_args results in "Too many arguments on command line" error

### ISSUE THREAD

**Issue by berglh** [vlaci/openconnect-sso#30]
Running Ubuntu 20.04.1, installed via pipx. Connection works fine if I don't specify openconnect_args. I'm guessing perhaps ordering of the args in the calling of `openconnect` might be the issue? Or perhaps something isn't escaped correctly in the `openconnect` connection args prior to adding the opeconnect_args arguments.

I've redacted organisational stuff with `**`.
```bash
berg@zen:~/.config/openconnect-sso$ openconnect-sso --server https://vpn4.router.**.edu.au openconnect_args -v
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=https://vpn4.router.**.edu.au name=
[info     ] Response received              [openconnect_sso.authenticator] id=main message=Please complete the authentication process in the AnyConnect Login window. title=Login
[info     ] Browser started                [webengine] startup_info=StartupInfo(url='https://vpn4.router.**.edu.au/+CSCOE+/saml/sp/login?tgname=**-VPN&acsamlcap=v2', credentials=None)
[info     ] Loading page                   [webengine] url=https://vpn4.router.**.edu.au/+CSCOE+/saml/sp/login?tgname=**-VPN&acsamlcap=v2
[info     ] Browser exited                 [openconnect_sso.browser.browser] 
[info     ] Response received              [openconnect_sso.authenticator] id=success message=
Too many arguments on command line
Usage:  openconnect [options] <server>
Open client for multiple VPN protocols, version v8.05-1
```
Additionally, when I run the connection with `opeconnect-sso ... -l DEBUG`, I am unable to complete the SAML form login. It just keeps showing the login form over and over. I am unable to validate what is happening at the `openconnect` call.

**Comment by vlaci** [comment]
you can specify additional args to openconnect after a `--`, e. g. `openconnext-sso -s server.com -- --csd-user nobdy`

**Comment by vlaci** [comment]
Feel free to reopen if your issue is still not resolved.

**Comment by berglh** [comment]
@vlaci Thanks for the response, I will give this another go tomorrow. I just wanted to add that my notifications on my phone had not alerted me to this one - sorry for the late reponse.
