### ISSUE TITLE
Working but logs many "Error: ipv4: Invalid values in header for route get request"

### ISSUE THREAD

**Issue by gatopeich** [vlaci/openconnect-sso#58]
First of all thanks for this alternative to CISCO's Anyconnect client with its backdoors and infamous security history :-)

It worked on 1st shot to me, on Ubuntu 20.04 LTS, despite spitting a lot of errors about `ip route`

I got this many times:
```
Error: ipv4: Invalid values in header for route get request.
Usage: ip route { list | flush } SELECTOR
...
```
Then this final error:
```
Error: any valid prefix is expected rather than "dev".
```
And my routing table is full of specific single-address routes, which I don't like but I hope I should be able to configure like with NerworkManager's "Route only addresses inside this VPN". Tips are welcome on this!

Anyway the SSO did work and I am connected and working thanks to it, THANKS!

**Comment by vlaci** [comment]
First of all, sorry for the late reply.

This wrapper only does tne SSO authentication, then it passes the resultant login ticket to openconnect itself. The networking setup is handled by [vpnc-scripts](https://gitlab.com/openconnect/vpnc-scripts).

**Comment by gatopeich** [comment]
Thanks for the tip!
