### ISSUE TITLE
stack trace when authentication fails

### ISSUE THREAD

**Issue by smoser** [vlaci/openconnect-sso#8]
When authentication fails with an error, I am hitting a stack trace like below.
The xml auth element contains `<error id="109">Single sign-on AnyConnect token verification failure.</error>`

    $ rm -Rf ~/.config/openconnect-sso/ ;
    $ _openconnect-sso_ --log-level=debug --server=xxx-xxx-xxxxxxx.xxxxx.xxx/xxx
    ...
    [info     ] Response received              [openconnect_sso.authenticator] id=main message=Please complete the authentication process in the AnyConnect Login window. title=Login
    [error   ] Error occurred during authentication. Invalid response type in state [openconnect_sso.authenticator] response=AuthRequestResponse(auth_id='main', auth_title='Login', auth_message='Please complete the authentication process in the AnyConnect Login window.', login_url='https://xxxxx-xxx-xxxxxxx-x.xxxxxx.xxx/+XXXXX+/saml/sp/login?tgname=SSL_Profile&acsamlcap=v2', login_final_url='https://xxxxx-xxx-xxxxxxx-x.xxxxx.xxx/+XXXXX+/saml_ac_login.html', token_cookie_name='acSamlv2Token', opaque=<Element opaque at 0x7f9580330cc8>) state=<STATE CompleteAuthentication>
    [debug    ] Entering state                 [openconnect_sso.authenticator] state=<STATE StartAuthentication>
    Traceback (most recent call last):
      File "openconnect-sso/bin/openconnect-sso", line 8, in <module>
        sys.exit(main())
      File "openconnect-sso/lib/python3.6/site-packages/openconnect_sso/cli.py", line 128, in main
        return _app.run(args)_
      File "openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 27, in run
        return asyncio.get_event_loop().run_until_complete(_run(args))
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 87, in _run
        session_token = await authenticate_to(selected_profile, credentials)
      File "openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 24, in authenticate
        self.auth_state = await self.auth_state.trigger()
      File "openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 64, in trigger
        logger.debug("Auth started", url=self.authenticator.host.vpn_url)
    AttributeError: 'NoneType' object has no attribute 'host'

**Comment by smoser** [comment]
Here is my hack fix... It is not acceptable as it is. I can submit a pull request if requested.  I'm not sure what the right way handle it is.  [hack-fix.patch.txt](https://github.com/vlaci/openconnect-sso/files/4036126/hack-fix.patch.txt)

**Comment by vlaci** [comment]
Thanks for the report. I'll look into it at the weekend.

**Comment by vlaci** [comment]
I have not forgotten to look into this but unfortunately haven't got time to dig into it.
