### ISSUE TITLE
Failed to open tun device: No such device

### ISSUE THREAD

**Issue by ATahma** [vlaci/openconnect-sso#9]
* Distro: Arch Linux Rolling 5.5.1
* Pip version: 19.3-1
* VPN server: securevpn.mcgill.ca
Attempts to fix the issue:
- Removed openconnect-sso, removed config files at `/home/[username]/.config/openconnect-sso` and reinstalled using `# pip install openconnect-sso`
- Reinstalled openconnect
- Tried connecting using another device (My android phone Cisco AnyConnect app) and it works without any hiccups
Here is my return log after trying to connect: 
```
[me@hostname]$ openconnect-sso --server securevpn.mcgill.ca
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=securevpn.mcgill.ca name=UNNAMED
[info     ] Response received              [openconnect_sso.authenticator] id=main message=Please complete the authentication process in the AnyConnect Login window. title=Login
[info     ] Browser started                [webengine] startup_info=StartupInfo(url='https://securevpn.mcgill.ca/+CSCOE+/saml/sp/login?tgname=DefaultWEBVPNGroup&acsamlcap=v2', credentials=None)
[info     ] Loading page                   [webengine] url=https://securevpn.mcgill.ca/+CSCOE+/saml/sp/login?tgname=DefaultWEBVPNGroup&acsamlcap=v2
[info     ] SIGNAL handler                 [webengine] 
[info     ] Exiting browser                [webengine] 
[info     ] Browser exited                 [openconnect_sso.browser.browser] 
[info     ] Response received              [openconnect_sso.authenticator] id=success message=
[sudo] password for me: 
Connected to 132.216.255.250:443
SSL negotiation with securevpn.mcgill.ca
Server certificate verify failed: signer not found
Connected to HTTPS on securevpn.mcgill.ca
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 300, Keepalive 20
Connected as 132.216.232.169, using SSL + LZS, with DTLS + LZS in progress
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS1.2)-(ECDHE-RSA)-(AES-256-GCM).
DTLS connection compression using LZS.
Failed to open tun device: No such device
Set up tun device failed
Unknown error; exiting.
```

I'd really appreciate if somebody could kindly point me in the right direction, I might be able to figure the solution out myself.

EDIT: Formatting

**Comment by vlaci** [comment]
The error is coming from the openconnect process. Have you upgraded the kernel recently? If so, please reboot your system and try again.

Background: Arch Linux has an issue that it cannot load kernel modules for the running system because the upgrade removes them.

**Comment by vlaci** [comment]
Is the issue still present?

**Comment by ATahma** [comment]
the issue was fixed upon updating and restarting -- thanks! Closing the issue
