### ISSUE TITLE
pytestrunner alias was removed

### ISSUE THREAD

**Issue by rhoriguchi** [vlaci/openconnect-sso#98]
Since commit https://github.com/NixOS/nixpkgs/commit/ddb7c7bd95a25d7c4101ee111d20fe16446d947c#diff-4878bf3fa499d7d0bab51ebe52427ba7ee884458535a7bbae5e31f245994dbf8R142 `pytestrunner` alias does not exist anymore.

```console
error: 'pytestrunner' has been renamed to/replaced by 'pytest-runner'
```

**Comment by hexop** [comment]
I am running into the same problem, I have submitted a pull request. Meanwhile, you can use [my fork](https://github.com/hexop/openconnect-sso) if you want to update nixpkgs
